code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dracula-theme.theme-dracula
code --install-extension formulahendry.code-runner
code --install-extension humao.rest-client
code --install-extension kuscamara.electron
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.anaconda-extension-pack
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension neuron.neuron-IPE
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension techer.open-in-browser